name: New Release

on:
  workflow_dispatch:

jobs:
  ls:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ls
        run: |
          git ls-files
          git log --oneline
